#!/bin/bash

export DISPLAY=${DISPLAY:-:0}
"${VFX_MELT:-melt}" -verbose -profile square_pal red.mlt out=22299 -filter webvfx:http://localhost:3001/filter-banner.html out=22299 -consumer sdl -consumer avformat:http://localhost:8001/publish/first?password=secret real_time=1 terminate_on_pause=0 f=webm vcodec=libvpx b=1000k s=720x570 acodec=libvorbis ab=128k g=0 me_method=zero flags2=fast preset=ultrafast tune=zerolatency crf=40 qmin=5



#!/bin/bash
#export DISPLAY=${DISPLAY:-:0}
#"${VFX_MELT:-melt}" red.mlt -consumer sdl mlt_profile=square_pal -filter webvfx:http://localhost:8080/filter-banner.html
#"${VFX_MELT:-melt}" -verbose "${VFX_SOURCE:-red.mlt}" out=299 \
 #  -filter webvfx:localhost:http://localhost:3000/filter-banner2.html \
  #  -consumer sdl
